### PR TITLE
fixing tracer version requirement

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@sean797 does this look sane?  I assume the '1' was a typo?

**Review by sean797 — APPROVED** [review]
ACK - Thanks @jlsherrill :-)

**Comment by ekohl** [comment]
This also needs to be backported to the katello 3.3 branch.

**Comment by jlsherrill** [comment]
@ekohl thanks for pointing that out!  This missed the branching just barely.  I've gone ahead and tagged -2 into the 3.3 tag, we don't normally cherry pick unless its katello, katello-repos, rubygem-katello, or katello-installer.

**Pull request merged**
