### PR TITLE
Fixes - #16476 - add capsule backup and restore

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by zjhuntin** [comment]
I was able to backup and restore a capsule successfully without any issue. ACK!

**Comment by chris1984** [comment]
Tested on downstream and works correctly to add to Zach's note

**Review by stbenjam — CHANGES_REQUESTED** [review]
We are no longer using the term 'capsule' beginning with Katello 3.3 - please rename this "foreman-proxy-backup"

**Comment by stbenjam** [comment]
Sorry :) Since we're about to merge the changes in the next couple of days it'd be good for this script to start out named right

**Comment by chris1984** [comment]
@stbenjam thanks :) corrected with the new names

**Comment by stbenjam** [comment]
Thanks! One thing, the old versions are still in the PR, and commit message needs updating  too

**Comment by stbenjam** [comment]
One other thought, we've tried to make the tools work regardless of where they are (capsule-remove is going away, katello-remove now does it all.  katello-service handles everything now too) - is there any chance katello-backup could just have a foreman proxy option?

**Comment by chris1984** [comment]
@stbenjam ack I will work on adjusting katello-backup to add a foreman proxy option. It only makes sense based on your last comment if the other tools are going away around capsule. Will recommit after I change and test with katello-backup

**Comment by ehelms** [comment]
@chris1984 planning to revisit this?

**Comment by chris1984** [comment]
@ehelms going to close this one out and work with @cfouant on putting this all into katello-backup/restore like Stephen suggested. Will open another pr either with her or with the suggested changes to katello-backup/restore.

**Pull request closed without merging**
