### PR TITLE
fixes #15366 - add yum-plugin-security dep to rhel5/6 packages (#234)

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by komidore64** [comment]
my name is adam price and i approve this pull request!

ack.

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
@jlsherrill looks to be passing now

**Comment by komidore64** [comment]
:boom:

**Pull request merged**
