### PR TITLE
fixes #14161 - adds online backup for pulp database, BZ170292

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by ehelms** [comment]
@cfouant as part of all of these backup/restore changes you are making could you add http://projects.theforeman.org/issues/11700 to your list so that users stop using the old/bad backup procedure?

**Comment by cfouant** [comment]
@ehelms - sure, how do I change documentation? I thought that was specifically for the doc writers.

**Comment by komidore64** [comment]
lgtm

**Comment by ehelms** [comment]
@cfouant I think you will need a rebase here

**Comment by cfouant** [comment]
@ehelms - done!

**Comment by ehelms** [comment]
ACK - thanks @cfouant !

**Pull request merged**
