### PR TITLE
Fixes #14673: Obsolete pulp-nodes* packages to resolve upgrade

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
I wonder if we'll have the same issue on the capsules?  

ACK

**Comment by ehelms** [comment]
Most likely it will, I guess we could attach an obsolete to the installer package? We currently use the same installer package on the server and capsule thus if we moved it there we would not need this change.

**Comment by jlsherrill** [comment]
Lets do that then, we'd have to add 'pulp-nodes-child' as well.

**Comment by ehelms** [comment]
Moved to the installer package

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
