### PR TITLE
Refs #18174 - Run katello-tracer-upload after reboot

### PR DESCRIPTION
**Pull request by sean797**

### CODE REVIEW

**Comment by sean797** [comment]
Requires https://github.com/Katello/katello-agent/pull/41

**Comment by jlsherrill** [comment]
released 2.9.1, feel free to add annex'd file to the pr now:  https://github.com/Katello/katello-agent/archive/2.9.1.tar.gz

**Comment by sean797** [comment]
Thanks @jlsherrill, done! 👍 

Also fuck off @theforeman-bot.

**Review by chris1984 — APPROVED** [review]
spec file looks good to me

**Comment by jlsherrill** [comment]
Thanks @sean797 will pull this into 3.3 as well

**Pull request merged**
