### PR TITLE
#358 allow globbing to catch the *.snar files during incremental backups

### PR DESCRIPTION
**Pull request by ericlake**

### CODE REVIEW

**Comment by ericlake** [comment]
Another approach would be to use the following on line 129
```
cp #{@options[:incremental]}/*.snar .` if @options[:incremental]
```

**Comment by sean797** [comment]
ok to test

**Comment by sean797** [comment]
[test]

**Review by sean797 — APPROVED** [review]

**Review by chris1984 — APPROVED** [review]

**Comment by ehelms** [comment]
Thanks @ericlake !

**Pull request merged**
