### PR TITLE
Fixes #20420,#20421 - add backup/restore/hostname-change to proxy

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by evgeni** [comment]
can those scripts please go into sbin? they are not usable by normal users anyways.

**Comment by johnpmitsch** [comment]
@evgeni should we do the same for [these](https://github.com/Katello/katello-packaging/blob/master/katello/katello.spec#L131-L135)? If so, should moving those be addressed in a separate PR?

**Comment by ehelms** [comment]
I think thats a fair request and doing the other scripts should be a separate PR.

**Comment by evgeni** [comment]
I'd do those in a separate PR.

**Comment by johnpmitsch** [comment]
@evgeni @ehelms updated to sbin

**Comment by evgeni** [comment]
you need to update the install step too: https://github.com/johnpmitsch/katello-packaging/blob/756c461978cd605e83308d431126c14189c266eb/katello/katello.spec#L92-L98

**Comment by johnpmitsch** [comment]
@evgeni if I update there, don't I have to move [these changes](https://github.com/Katello/katello-packaging/pull/488) to this PR as well?

**Comment by evgeni** [comment]
i'd say get https://github.com/Katello/katello-packaging/pull/488 merged with all the needed changes, then this PR will build again fine :)

**Comment by ehelms** [comment]
[test]

**Pull request merged**
