### PR TITLE
Require bastion 4.X

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Dependent on https://github.com/theforeman/foreman-packaging/pull/1462

**Comment by ehelms** [comment]
@jlsherrill I cannot build bastion for nightly with the foreman breakages, but you will need this for 3.3.

**Comment by jlsherrill** [comment]
yep, i will pull this into 3.3.  Testing the removal of the gemspec on a 3.2 build right now (since both 3.3 and nightly won't build):  http://koji.katello.org/koji/taskinfo?taskID=583211

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@jlsherrill need this now that its green to continue with nightlies

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
