### PR TITLE
Update foreman_pipeline to 0.1.0

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by xprazak2** [comment]
Still failing on missing dependencies for qpid on RHEL6, I noticed katello's nightly builds have been lately failing for the same reason, anything I can do to fix it?

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@xprazak2 we no whave EL6 builds working for 3.2, I'll give this a test once more and if it fails look at removing EL6 for nightly.

**Comment by xprazak2** [comment]
@ehelms, ping. I removed EL6 from nightly and we are green now.

**Comment by jlsherrill** [comment]
@xprazak2 hey sorry this conflicts now that el6 has been removed, mind rebasing and we'll get it in really quickly!

**Comment by xprazak2** [comment]
@jlsherrill, I rebased and tests are passing, can we get it in?

**Comment by xprazak2** [comment]
@jlsherrill ping

**Comment by jlsherrill** [comment]
arg sorry, this slipped through.  ACK Merging, will build!

**Comment by jlsherrill** [comment]
ugg build is currently failed on an issue with the foreman nightly, will try back in a day or so

**Pull request merged**
