### PR TITLE
use prever to override gem paths in katello gem

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
For realz this time, green build to prove it:  http://koji.katello.org/koji/taskinfo?taskID=367263

**Comment by ehelms** [comment]
Should this go in master first?

**Comment by jlsherrill** [comment]
I was going to update https://github.com/Katello/katello-packaging/pull/91 with these changes, I can do that first if you prefer

**Comment by ehelms** [comment]
Ja - please to update master PR first

**Comment by ehelms** [comment]
ACK

**Pull request merged**
