### PR TITLE
Fixes #20922 - use highline for user promting

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
rebased

**Review by sean797 — APPROVED** [review]
ACK. Thanks @evgeni 👍 Sorry about the late review

**Comment by ehelms** [comment]
highline is not default ruby is it? So the spec files that include this file will need to require this package now?

**Comment by evgeni** [comment]
@ehelms you are right, even though katello-backup was using highline before, w/o explicitly adding that dep. added now.

**Comment by evgeni** [comment]
[test]

**Comment by ehelms** [comment]
These packages and code have all moved to foreman-packaging `rpm/develop` under a `katello` subfolder. Please re-open your PR against it to ensure there is no data loss between the repositories. The code in this repository will be subsequently removed -- https://github.com/Katello/katello-packaging/pull/575

**Comment by evgeni** [comment]
moved to https://github.com/theforeman/foreman-packaging/pull/1928

**Pull request closed without merging**
