### PR TITLE
Fixes #15845 - add cronjob to clean puppet envs

### PR DESCRIPTION
**Pull request by jlsherrill**
and add a new capsule subpackage to katello to install it on capsules

### CODE REVIEW

**Comment by ehelms** [comment]
Where are you planning to include this for installation?

**Comment by jlsherrill** [comment]
@ehelms was thinking of updating the capsule install and upgrade docs.  Any other thoughts?

**Comment by ehelms** [comment]
ACK -- @jlsherrill planning a follow up PR that has the katello-capsule RPM require the installer so we can instruct users to just install this package?

**Comment by jlsherrill** [comment]
pulp issue filed:  https://pulp.plan.io/issues/2108

Will do followup PR

**Pull request merged**
