### PR TITLE
fixes #11261 - wait a little after starting httpd

### PR DESCRIPTION
**Pull request by stbenjam**
see https://github.com/Katello/katello/pull/5389

### CODE REVIEW

**Comment by mccun934** [comment]
seems entirely reasonable to me, surprised we didn't need this earlier

**Comment by jlsherrill** [comment]
would a wait_for_url work in this case?  Not opposed to the change, just curious

**Comment by mccun934** [comment]
@jlsherrill what URL would we pick?

**Comment by jlsherrill** [comment]
http://localhost:80  ?

I guess it depends on why its failing if you need to try to hit pulp or not

**Comment by mccun934** [comment]
localhost:80 makes sense, that is pretty service agnostic. @stbenjam thoughts?

**Comment by stbenjam** [comment]
@jlsherrill  Yea, I was wondering if we should hit a url or not.  http://localhost:80 hits foreman, and might take a while for the app to load.  Could be many minutes in some cases.

I figured a short sleep was enough, just because the problem here is such a tiny, tiny window,  where the init script creates the lockfile but the pidfile isn't there yet.

**Comment by jlsherrill** [comment]
@stbenjam ahhh if that is the problem then i'm good with this solution,  ACK

**Comment by stbenjam** [comment]
Thanks. I did file a BZ for it too, in case they want to fix the init script.  https://bugzilla.redhat.com/show_bug.cgi?id=1248724

**Pull request merged**
