### PR TITLE
Include capsule-certs-generate on all installations

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@ehelms I could have not set things up correctly, but I am not seeing the capsule-certs-generate package installed

box config:

```
kojiscratch:
  box: centos7
  shell: 'yum -y install ruby && cd /vagrant && ./setup.rb'
  options: --scenario=katello-devel --koji-task 508233
  installer: --katello-devel-github-username johnpmitsch -v
```

checking for packages:

```
[vagrant@kojiscratch ~]$ rpm -qa | grep capsule-certs-generate
[vagrant@kojiscratch ~]$ rpm -qa | grep foreman-installer-katello-devel
foreman-installer-katello-devel-3.2.0-1.nightly.201607122230gitba43845.el7.noarch
```

**Comment by ehelms** [comment]
The RPM there doesn't look like the one from the scratch build.

**Comment by johnpmitsch** [comment]
@ehelms any ideas what is wrong with my config?

**Comment by ehelms** [comment]
Can you verify a repo was created locally with a repo file and contains the scratch build? You may need to set the priority=1 on the repo file if it exists.

**Comment by johnpmitsch** [comment]
@ehelms this time I used build [508235](http://koji.katello.org/koji/taskinfo?taskID=508235), it looks like it included the correct scratch build, but still no capsule-certs-generate

```
[root@kojiscratch ~]# rpm -qa | grep foreman-installer-katello-devel
foreman-installer-katello-devel-3.2.0-1.nightly.201608032312git34a4530.el7.noarch
[root@kojiscratch ~]# rpm -qa | grep capsule
[root@kojiscratch ~]# 
```

here is the yum repo file (unedited by me)

```
[root@kojiscratch ~]# cat /etc/yum.repos.d/koji-scratch-repo-for-508235.repo 
[koji-scratch-repo-for-508235]
name=Repository for Koji Scratch Repo for 508235
baseurl=file:///vagrant/repo
enabled=1
gpgcheck=0
protect=1
priority=1
```

Let me know if that wasn't the correct build or what else I can change to get an accurate test

**Comment by ehelms** [comment]
[test]

**Pull request closed without merging**
