### PR TITLE
Refs #12527 - build agent and repo rpms for f23 and f22

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
What about comps updates?

**Comment by jlsherrill** [comment]
Good catch, updated

**Comment by ehelms** [comment]
ACK -- I assume you'll remove those tags and buildroots in koji as well as clean up fedorapeople repos

**Comment by jlsherrill** [comment]
@ehelms yeah, i'll remove the nightly tags and what not.

**Pull request merged**
