### PR TITLE
Have katello-backup report on times

### PR DESCRIPTION
**Pull request by jcpunk**
This PR adds the timestamp of start/end of the backup for end users.

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@jcpunk woudl you mind opening a Redmine issue http://projects.theforeman.org/projects/katello-packaging/issues and linking it in the commit message so we can pull this into a the next release for you?

**Comment by jcpunk** [comment]
Done http://projects.theforeman.org/issues/14976

**Comment by ehelms** [comment]
Thanks @jcpunk !

**Pull request merged**
