### PR TITLE
Fixes #20431 - ignore services in the static state

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@beav Please to take a look at this.

**Comment by beav** [comment]
looks good to me. This removes el6 support which is fine by me, but you may want to mention it in the commit message.

**Comment by beav** [comment]
ACK aside from adding upstart removal note in commit message

**Comment by evgeni** [comment]
ACK on the change, but I also think we should fix `katello-remove` to either be a proper `katello-uninstaller` or stop pretending being one ;)

**Comment by ehelms** [comment]
@evgeni want to file a separate issue to tackle your comment?

**Comment by ehelms** [comment]
Updated the commit message, merging now

**Comment by evgeni** [comment]
sure: http://projects.theforeman.org/issues/20441

**Pull request merged**
