### PR TITLE
Fixes #19281 - Move katello commands to sbin

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by evgeni** [comment]
you need to adapt the install part too:
https://github.com/johnpmitsch/katello-packaging/blob/1625bec3f07aec345ce8de9a194224002d8c4672/katello/katello.spec#L92-L98

**Comment by johnpmitsch** [comment]
@evgeni updated, I don't know if we want katello-service moved as well

**Comment by evgeni** [comment]
Given `katello-service status` works as a user, I'd vote for leaving it in bin. @ehelms?

**Comment by ehelms** [comment]
What user is going to run that? I say keep them all together.

**Comment by johnpmitsch** [comment]
updated

**Review by ehelms — APPROVED** [review]
@evgeni what say ye?

**Comment by evgeni** [comment]
I'd say my CDO kicks in online 92 and the fact that the install and files sections are sorted differently, but otherwise I'm good!

**Pull request merged**
