### PR TITLE
Allow foreman-tasks below 1.0.0

### PR DESCRIPTION
**Pull request by ehelms**
Prevents Katello RC1 from installing

### CODE REVIEW

**Comment by sean797** [comment]
[test]

I'm not sure why this failed, the logs don't seem to be at http://koji.katello.org/koji/taskinfo?taskID=622217 anymore.

**Comment by jlsherrill** [comment]
[test]

**Comment by ares** [comment]
[test] could someone please take a look at this? It blocks https://github.com/Katello/katello-packaging/pull/426 and is required after https://github.com/Katello/katello/pull/6724 has been merged.

**Comment by jlsherrill** [comment]
@ares yes, i've been working on it while doing other things.  There were about 4 different slightly dependent things breaking the current build including:

This is currently blocked by a katello update needed to pull in a new runcible due to the rest-client update in foreman (the runcible change has already been made and released).
That was blocked by a transient unit test failure caused by the minitest upgrade in foreman.

All of these things kinda pilled up due to ehelms outage and me being out for a couple of weeks, but we're finally seeing the light at the end of the tunnel, as the transient test failure has been resolved paving the way for the new runcible requirement bump, and that being able to be added here.  Hopefully nothing new has popped up in the past week while this work has been done.

**Comment by jlsherrill** [comment]
note, i opened a pr here: https://github.com/Katello/katello-packaging/pull/435 with the runcible + foreman-tasks changes, however something else is now failing.  investigating.

**Comment by ares** [comment]
Thanks for info Justin

**Comment by jlsherrill** [comment]
closing now that https://github.com/Katello/katello-packaging/pull/435 is merged

**Pull request closed without merging**
