### PR TITLE
Update rubygem-hammer_cli_katello to 0.0.21

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by komidore64** [comment]
successful scratch builds: [EL6](http://koji.katello.org/koji/taskinfo?taskID=421100), [EL7](http://koji.katello.org/koji/taskinfo?taskID=421102)

**Comment by ehelms** [comment]
Looks like you added the binary instead of using git annex.

**Comment by komidore64** [comment]
ugh

**Comment by ehelms** [comment]
ACK - thanks @komidore64 !

**Pull request merged**
