### PR TITLE
Refs #13589 - replace gofer plugin config file

### PR DESCRIPTION
**Pull request by jlsherrill**
this config file is not meant to ever be customized by the user, but is needed
for the plugin to function

### CODE REVIEW

**Comment by ehelms** [comment]
Do you want to go ahead and bump the release here too?

**Comment by jlsherrill** [comment]
I figured we'd wait till release time to tag, pull in the new release, and bump the version in case there are other changes that come in.  I was more making this change so we didn't forget.

**Comment by jlsherrill** [comment]
We'll also need a new updated version of gofer to support the feature in https://github.com/Katello/katello-agent/pull/34  

It should appear soon with pulp 2.8

**Comment by ehelms** [comment]
Groovy - ACK

**Comment by jlsherrill** [comment]
Need to add a dependency on gofer 2.7

**Comment by jlsherrill** [comment]
2.7.4 to be exact

**Comment by ehelms** [comment]
Looks like gofer 2.7.5 is staged to go into nightlies with the latest Pulp update if you want to fix this PR up and we can get it merged.

**Comment by jlsherrill** [comment]
I figured i'd go ahead and bump the version of katello-agent.  Thoughts on what i should bump it to?  3.0 ?

**Comment by ehelms** [comment]
Is this a backwards incompatible change?

**Comment by jlsherrill** [comment]
It should not be afaik

**Comment by ehelms** [comment]
Will this katello-agent still work with Katello 2.4 for example? If so, then I guess I don't see a reason for a major bump.

**Comment by jlsherrill** [comment]
Well there could be  two questions that you are asking

a)  Will the new katello agent work with pulp 2.6 consumer code against pulp 2.8
No idea, we never test this.  If i had to wildly guess I would say yes.

b) Will the new katello agent work with pulp 2.6 consumer code against pulp 2.6
Yes, it should

EDIT: fixed question b)

**Comment by ehelms** [comment]
So I guess no reason to bump to 3.0 unless we are just trying to keep katello-agent versioning the same as the main application?

**Comment by jlsherrill** [comment]
@ehelms katello-agent 2.5.0 releaesd and this now uses that

**Comment by ehelms** [comment]
This has the binary and not the git annexed file.

**Comment by jlsherrill** [comment]
@ehelms updated

**Comment by ehelms** [comment]
APJ

**Pull request merged**
