### PR TITLE
Fixes #12137 - Stops katello services in right order

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ehelms** [comment]
This needs to be linked to a Redmine issue and not a Bugzilla

**Comment by adamruzicka** [comment]
@ehelms Copied the bugzilla to redmine and linked it all together

**Comment by ehelms** [comment]
Thanks @adamruzicka , @stbenjam do you mind reviewing this change?

**Comment by stbenjam** [comment]
I guess it is in our commit style to allow us to include BZ in addition to the redmine http://www.katello.org/developers/style/git_commit_messages.html, although I wish we wouldn't do that

Anyway,looks good - ACK from me

**Comment by ehelms** [comment]
Thanks @adamruzicka !

**Pull request merged**
