### PR TITLE
Fixes #15982 - adding custom python-urllib3

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
No epels? No fun.

**Comment by jlsherrill** [comment]
its a base RHEL package, no epels indeed!  We'll just need to include it until 7.3 and 6.9 come out I believe

**Comment by ehelms** [comment]
What version of python-urllib3 was the patch officially included in?

**Comment by jlsherrill** [comment]
Was committed upstream:  https://github.com/shazow/urllib3/pull/830

but has not made a stable release yet

**Comment by ehelms** [comment]
ACK

**Comment by jeremycline** [comment]
@ehelms It's in urllib3-1.16 (which is released)

**Pull request merged**
