### PR TITLE
Cherry Picks for 3.4 RC2

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by sean797** [comment]
Should https://github.com/Katello/katello-packaging/commit/55b9c716a1a7d2291983518f94c356112055c79f also be include?

**Comment by ehelms** [comment]
They are not currently marked against 3.4.0. I'd suggest recommending them at triage on Wednesday for the next round.

**Review by sean797 — APPROVED** [review]
I cant seem to set those against 3.4 only foreman release versions are listed. http://projects.theforeman.org/issues/19155

**Comment by ehelms** [comment]
Oh, you should move those to the Katello project. We've stopped using that packaging subproject (need to get it removed).

**Comment by jlsherrill** [comment]
@sean797 i went ahead and moved it to 3.4, it should appear in rc3

ACK

**Comment by sean797** [comment]
Thanks @jlsherrill - I don't have permission to change the Project 👍

**Pull request merged**
