### PR TITLE
Stop building katello-sam RPM

### PR DESCRIPTION
**Pull request by ehelms**
This removes katello-sam as an RPM and thus removes dependencies on
rubygem-foreman_sam as well. If this ever needs to be ressurected,
this commit can be used as a template.

### CODE REVIEW

**Comment by ehelms** [comment]
This begs the question do we remove the cli and the installer parts as well? @thomasmckay @komidore64 @mccun934

**Comment by jlsherrill** [comment]
ACK  remove all the sam

**Comment by ehelms** [comment]
@jlsherrill updated this to just remove all SAM

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
