### PR TITLE
rebuild for ror42

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
FYI this will only try and build the first 5, we can change this upper limit just hadn't need a reason to before (was put in place to prevent overload from mass changes).

**Comment by beav** [comment]
APJ

**Comment by jlsherrill** [comment]
trimmed to 5 builds and opened a 2nd pr for the rest non-rails engine updates

**Comment by jlsherrill** [comment]
@beav mind a quick re-review?

**Comment by beav** [comment]
@jlsherrill ACK lgtm

**Pull request merged**
