### PR TITLE
Refs #10291 - Remove elasticsearch from completion script

### PR DESCRIPTION
**Pull request by sean797**
This was missed on a previous PR #82

### CODE REVIEW

**Comment by ehelms** [comment]
Small thing but could you update this to Refs since it's in addition to an already closed issue (or open a new issue)? Thanks!

**Comment by sean797** [comment]
You replied to quickly ;) http://projects.theforeman.org/issues/10291

**Comment by ehelms** [comment]
Yea - just update the commit message and PR to say 'Refs #10291'

**Comment by sean797** [comment]
Sorry about all that, I'm still kind of new to git and got a lot to learn. Got there in the end!

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@sean797 if you join the Katello organization and set your membership to public, your PRs will get tested automatically in the future

**Comment by sean797** [comment]
@ehelms  Yes, that sound good. Do I have to be invited to join?

**Comment by ehelms** [comment]
ACK - thanks @sean797

**Pull request merged**
