### PR TITLE
Fixes #20404 - require simplejson on EL5

### PR DESCRIPTION
**Pull request by evgeni**
Python 2.4 does not yet have the json module built in.

### CODE REVIEW

**Comment by evgeni** [comment]
[test]

**Comment by jlsherrill** [comment]
I released a new katello-agent with your fix: https://github.com/Katello/katello-agent/releases/tag/3.0.1

mind incorporating it here?

**Comment by evgeni** [comment]
yepp, will do. thanks for releasing!

**Comment by evgeni** [comment]
there we go!

**Review by jlsherrill — APPROVED** [review]
ACK

**Pull request merged**
