### PR TITLE
Refs #16134 - add new subpackage for sub-man plugin

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
created as a subpackage in case the user doesn't want katello-agent installed.  katello-agent requires it though.

**Comment by jlsherrill** [comment]
note this will fail until https://github.com/Katello/katello-agent/pull/37 is merged, tagged, and this pr version bumps.

**Comment by ehelms** [comment]
Is this ready to be reviewed now?

**Comment by jlsherrill** [comment]
@ehelms yes!

**Comment by ehelms** [comment]
Looks good! ACK

**Pull request merged**
