### PR TITLE
Updating rubygem-hammer_cli_import to 0.10.22

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
Can you reset the release? a commit message of "Updating rubygem-hammer_cli_import to 0.10.22" would be more descriptive

**Comment by jlsherrill** [comment]
@ehelms good catch, updated

**Comment by ehelms** [comment]
ACK

**Comment by lpramuk** [comment]
I miss update in Changelog

**Pull request merged**
