### PR TITLE
 more ror42 builds

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by beav** [comment]
APJ

**Comment by beav** [comment]
may need another swap to add `_ror` on a Requires:

```
DEBUG util.py:264:  Getting requirements for tfm-rubygem-foreman_pipeline-0.0.8-3.git.186.44accc9.el7.src
DEBUG util.py:264:   --> foreman-plugin-1.12.0-0.develop.201604261505git6b541a0.el7.noarch
DEBUG util.py:264:   --> tfm-rubygem-jenkins_api_client-1.4.1-3.el7.noarch
DEBUG util.py:264:   --> tfm-rubygem-foreman_deployments-0.0.1-1.fm1_11.el7.noarch
DEBUG util.py:264:   --> tfm-rubygem-net-ssh-3.0.2-2.el7.noarch
DEBUG util.py:264:  Error: No Package found for tfm-rubygem(net-ssh) < 3.0
```

**Comment by jlsherrill** [comment]
Actually it looks like foreman is now shipping >= 3.0  http://koji.katello.org/koji/buildinfo?buildID=30815

**Comment by jlsherrill** [comment]
removed foreman_pipeline, as it needs a new gem release to pull in https://github.com/theforeman/foreman_pipeline/commit/715a7728288ab64536d1b93445c6bad8de7e7c43

**Comment by ehelms** [comment]
@xprazak2 note comment https://github.com/Katello/katello-packaging/pull/212#issuecomment-214851041

**Comment by jlsherrill** [comment]
i also opened https://github.com/theforeman/foreman_pipeline/issues/45

**Comment by beav** [comment]
ACK

**Pull request merged**
