### PR TITLE
Fixes #19074 upgrade bastion to 5.0.0

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/19074

### CODE REVIEW

**Comment by waldenraines** [comment]
See also https://github.com/theforeman/rfcs/pull/13

**Comment by ehelms** [comment]
Thanks - will merge once bastion has been released to foreman-plugins.

**Comment by waldenraines** [comment]
> Thanks - will merge once bastion has been released to foreman-plugins.

Thanks!

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
Thanks @waldenraines !

**Pull request merged**
