### PR TITLE
Bumping nightly builds to 3.4.0

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
Installer bump as well?

**Comment by jlsherrill** [comment]
Thanks, i knew i missed something.  This is expected to fail as the nightly rpms are broken due to foreman.  I suggest we still merge this if the rubygem-katello rpm is the only breakage

**Comment by ehelms** [comment]
:+1:

**Review by ehelms — APPROVED** [review]

**Comment by jlsherrill** [comment]
Everything passed but rubygem-katello, merging!

**Pull request merged**
