### PR TITLE
Update rubygem-hammer_cli_katello to 0.0.22

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by beav** [comment]
I had some trouble with ./setup_sources.sh that was unrelated to this patch, but this patch seems reasonable.

ACK

**Comment by ehelms** [comment]
@beav if you click through the testing that is run, it will try and setup sources and build this in koji which serves as a check that the thing in question was released properly upstream, can be resolved and the RPM build passes successfully.

**Comment by ehelms** [comment]
ACK - thanks @komidore64 !

**Comment by beav** [comment]
@ehelms cool, good to know :rainbow:

**Pull request merged**
