### PR TITLE
Update foreman_virt_who_configure to 0.0.2

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
having this tagged with 3.4 would be good too

**Comment by ares** [comment]
In which project I should create a redmine issue for this? Btw foreman-packaging does not require issue numbers for packaging changes (just one thing that could possibly be unified)

Seems like other deps break the build, I suppose this is not caused by this PR.

```
DEBUG util.py:388:  Error: Package: tfm-rubygem-runcible-1.11.0-1.el7.noarch (build)
DEBUG util.py:388:             Requires: tfm-rubygem(rest-client) < 2.0.0
DEBUG util.py:388:             Installing: tfm-rubygem-rest-client-2.0.1-1.el7.noarch (build)
DEBUG util.py:388:                 tfm-rubygem(rest-client) = 2.0.1
DEBUG util.py:388:  Error: Package: tfm-rubygem-katello-3.5.0-.201704051909gite95fc6d1.nightly.el7.noarch (build)
DEBUG util.py:388:             Requires: tfm-rubygem(foreman-tasks) < 0.9.0
DEBUG util.py:388:             Installing: tfm-rubygem-foreman-tasks-0.9.1-1.fm1_16.el7.noarch (build)
DEBUG util.py:388:                 tfm-rubygem(foreman-tasks) = 0.9.1
DEBUG util.py:388:  Error: Package: tfm-rubygem-katello-3.5.0-.201704051909gite95fc6d1.nightly.el7.noarch (build)
DEBUG util.py:388:             Requires: tfm-rubygem(foreman-tasks) < 0.9.0
DEBUG util.py:388:             Available: tfm-rubygem-foreman-tasks-0.9.1-1.fm1_16.el7.noarch (build)
DEBUG util.py:388:                 tfm-rubygem(foreman-tasks) = 0.9.1
```

**Comment by ares** [comment]
Btw with 3.4 it seems to work fine http://koji.katello.org/koji/taskinfo?taskID=624554

**Comment by jlsherrill** [comment]
@ares yes, the nightly build issue is known and currently being worked on.  Let me see if i can get it resolved in the next few days, if not we can go ahead and merge + build for 3.4 only

**Comment by jlsherrill** [comment]
[test]

**Comment by ares** [comment]
better but still not good

```
foreman_virt_who_configure-0.0.2-1.fm1_16.git.3.fc4ec9c.el7.src.rpm']
DEBUG util.py:314:  Executing command: ['/usr/bin/yum-builddep', '--installroot', '/var/lib/mock/katello-nightly-rhel7-build-147737-115996/root/', '/var/lib/mock/katello-nightly-rhel7-build-147737-115996/root///builddir/build/SRPMS/tfm-rubygem-foreman_virt_who_configure-0.0.2-1.fm1_16.git.3.fc4ec9c.el7.src.rpm', '--setopt=tsflags=nocontexts'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'echo -n "<mock-chroot>"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin'}
DEBUG util.py:264:  Getting requirements for tfm-rubygem-foreman_virt_who_configure-0.0.2-1.fm1_16.git.3.fc4ec9c.el7.src
DEBUG util.py:264:   --> foreman-assets-1.16.0-0.develop.201704241650git7964a13.el7.noarch
DEBUG util.py:264:   --> foreman-plugin-1.16.0-0.develop.201704241650git7964a13.el7.noarch
DEBUG util.py:264:   --> tfm-rubygem-katello-3.5.0-.201704051909gite95fc6d1.nightly.el7.noarch
DEBUG util.py:264:   --> Already installed : rh-ruby22-ruby-libs-2.2.2-12.el7.x86_64
DEBUG util.py:264:   --> Already installed : rh-ruby22-ruby-2.2.2-12.el7.x86_64
DEBUG util.py:264:   --> rh-ruby22-rubygems-devel-2.4.5-12.el7.noarch
DEBUG util.py:264:  Error: Package: tfm-rubygem-katello-3.5.0-.201704051909gite95fc6d1.nightly.el7.noarch (build)
DEBUG util.py:264:             Requires: tfm-rubygem(foreman-tasks) < 0.9.0
DEBUG util.py:264:             Installing: tfm-rubygem-foreman-tasks-0.9.1-1.fm1_16.el7.noarch (build)
DEBUG util.py:264:                 tfm-rubygem(foreman-tasks) = 0.9.1
DEBUG util.py:264:  Error: Package: tfm-rubygem-katello-3.5.0-.201704051909gite95fc6d1.nightly.el7.noarch (build)
DEBUG util.py:264:             Requires: tfm-rubygem(foreman-tasks) < 0.9.0
DEBUG util.py:264:             Available: tfm-rubygem-foreman-tasks-0.9.1-1.fm1_16.el7.noarch (build)
DEBUG util.py:264:                 tfm-rubygem(foreman-tasks) = 0.9.1
DEBUG util.py:264:   You could try using --skip-broken to work around the problem
DEBUG util.py:264:   You could try running: rpm -Va --nofiles --nodigest
DEBUG util.py:354:  Child return code was: 1
```

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
Thanks @ares !

**Comment by ares** [comment]
I see the package built in koji but I don't see it in https://fedorapeople.org/groups/katello/releases/yum/nightly/katello/el7/x86_64/ is there something pending?

**Comment by jlsherrill** [comment]
@ares the pipeline is currently broken:   http://ci.theforeman.org/view/Katello%20Pipeline/ and the nightlies only get published to fedorapeople.org on successful runs, you can see it here in the koji staging repo:  http://koji.katello.org/releases/yum/katello-nightly/katello/el7/x86_64/

The pipeline is failing due to some puppet module updates for the installer, i think we are only waiting on https://github.com/Katello/puppet-foreman_proxy_content/pull/122 to go in

**Comment by ares** [comment]
Thanks Justin

**Pull request merged**
