### PR TITLE
Fixes #17254 - remove katello-common last

### PR DESCRIPTION
**Pull request by sean797**

### CODE REVIEW

**Comment by stbenjam** [comment]
I'd prefer if we didn't say "Success!" and then do another thing.  Success should indicate whether everything succeed or failed.

**Comment by sean797** [comment]
@stbenjam that makes sense! Updated :+1:

**Comment by stbenjam** [comment]
So if I understand correctly, this is supposed to prevent removing katello-remove if something failed? 

I don't see any checks if the other commands failed, so you'll still reach the end  and remove katello-common regardless of what happens.

**Comment by sean797** [comment]
Ah sorry @stbenjam that was kind of stupid of me. Updated again :-)

**Comment by ehelms** [comment]
@sean797 sorry for the delay, this will need a rebase

**Comment by sean797** [comment]
Closing, I don't think the original error will happen now that it's been re-written in Ruby.

**Pull request closed without merging**
