### PR TITLE
Update foreman_virt_who_configure to 0.1.0

### PR DESCRIPTION
**Pull request by ares**
This should be also cherry-picked into KATELLO-3.4 branch, should I open separate PR for it after it's merged?

### CODE REVIEW

**Comment by jlsherrill** [comment]
ACK thanks @ares !

**Comment by ares** [comment]
Sorry to be the troublemaker all the time, but I don't see this built in koji http://koji.katello.org/koji/packageinfo?packageID=1258 and it was not cherry-picked to KATELLO-3.4 either, is there something I missed?

**Comment by jlsherrill** [comment]
Whoops! looks like those didn't get built yesterday, should be now: 
koji.katello.org/koji/buildinfo?buildID=38821
http://koji.katello.org/koji/buildinfo?buildID=38820 

sorry about that!

**Comment by ares** [comment]
Thanks @jlsherrill, now I see it in nightlies but as I mentioned, it should also be in 3.4 repos. I see it has been built into katello-3.4-rhel7 tag http://koji.katello.org/koji/buildinfo?buildID=38820 but I don't see it in 3.4 repos https://fedorapeople.org/groups/katello/releases/yum/3.4/katello/el7/x86_64/ I only see it in nightlies. Since there's not even 0.0.2, is there some mashing issue?

**Comment by jlsherrill** [comment]
hey @ares it should show up there once 3.4.0 is released, it is still on rc2

**Comment by ares** [comment]
ah ok, makes sense, I though plugins could be release asynchronously as in foreman-packaging but it's if it will be released with 3.4. thank you!

**Pull request merged**
