### PR TITLE
Faster katello backup

### PR DESCRIPTION
**Pull request by evgeni**
- don't compress pulp data -- RPMs are already compressed
- do not be verbose when calling tar

### CODE REVIEW

**Comment by evgeni** [comment]
rebased after ES removal

**Comment by dLobatog** [comment]
[test] - this triggers our CI

**Comment by ehelms** [comment]
Looks good to me -- @evgeni can you squash please?

**Comment by evgeni** [comment]
@ehelms squashed and pushed.

**Comment by dLobatog** [comment]
[test] ,

**Comment by dLobatog** [comment]
@ehelms :+1: imo

**Comment by ehelms** [comment]
ACK - thanks @evgeni !

**Pull request merged**
