### PR TITLE
Fixes #13017 - remove priorities to use qpid from epel

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
See comments here -- https://github.com/Katello/katello-packaging/pull/162

**Comment by jlsherrill** [comment]
@ehelms updated

**Comment by ehelms** [comment]
ACK - @jlsherrill do you want to merge and rebuild the packages or me?

**Comment by jlsherrill** [comment]
Problem found with qdrouterd, so holding off on merging

**Comment by ehelms** [comment]
ACK

**Pull request merged**
