### PR TITLE
Fixes #15271: Obsolete removed gutterball gems

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by bbuckingham** [comment]
APJ

**Comment by beav** [comment]
from koji

```
rake aborted!
Gem loading error: Could not find 'foreman-tasks' (~> 0.7.18) - did find: [foreman-tasks-0.7.17]
```

**Comment by ehelms** [comment]
[test]

**Comment by beav** [comment]
ACK, thanks @ehelms

**Pull request merged**
