### PR TITLE
Bump foreman-tasks requirement to less than 1.0.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This is targeted at 3.4 to fix RC1

**Comment by jlsherrill** [comment]
Shouldn't this be fixed in the gemspec first? (or did i just miss it in my searching)

**Comment by ehelms** [comment]
This? https://github.com/Katello/katello/commit/74dbf7581041b31de015daf99b3ad0abf668f452

**Comment by jlsherrill** [comment]
APJ

**Pull request merged**
