### PR TITLE
Change rubygem-katello to source and build like other rubygems.

### PR DESCRIPTION
**Pull request by ehelms**
This removes the idea of grabbing the source from github since that
was originally done to help facilitate nightlies. Those will now be
built from archives on Jenkins that build a gem.

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by stbenjam** [comment]
ACK

**Comment by stbenjam** [comment]
-ACK per discussion in https://github.com/Katello/katello-packaging/pull/46

**Comment by ehelms** [comment]
Updated to the following strategy:

1) Removed any source being checked in
2) Set version to what current master's version is expected to me
3) Source must be acquired to build, so, for example, nightlies would be built like this:

```
tito release -o /home/ehelms/workspace/katello-packaging/rel-eng/build/ --scratch --arg jenkins_job=test_katello_core --arg jenkins_job_id=lastSuccessfulBuild koji-katello-nightly --debug
```

**Comment by ehelms** [comment]
I may have to update the PR testing to test updates for this setup properly. Will look into that

**Comment by ehelms** [comment]
Iterated on changes necessary for this including updates to Jenkins, this is green now for review! Then I can update the pipeline to properly build this from Jenkins.

**Comment by ehelms** [comment]
@stbenjam if you have time to re-review so I can get the pipeline re-rolling properly, that'd be great

**Comment by stbenjam** [comment]
ACK

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
