### PR TITLE
Remove i18n_data dependency on rubygem-katello

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by stbenjam** [comment]
Theoretically, the other PR I just ACK'd sets rubygem-katello to 2.2.2,  which does require i18n_data.  
Merging this would break the RPM, no?

**Comment by ehelms** [comment]
Excellent question! I am going to re-work the other PR a bit and go ahead and merge this.

**Comment by stbenjam** [comment]
Ok ACK

**Pull request merged**
