### PR TITLE
building 3.1.0.rc1 rubygem-katello

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
Looks like your 3.1 tags are missing the foreman tag inheritances -- http://koji.katello.org/koji/taginfo?tagID=1078

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
ACK

**Pull request merged**
