### PR TITLE
Fixes #19126 - collect katello-reverse-proxy_access_ssl.log

### PR DESCRIPTION
**Pull request by lzap**
I'd like to ask backport into stable. Thanks.

### CODE REVIEW

**Comment by lzap** [comment]
I think you guys need to move "foreman_debug" redmine component from Katello project. It's all here.

**Comment by ehelms** [comment]
Move it to where?

**Comment by lzap** [comment]
Sorry, I mean I think katello-debug needs to be component of foreman-packaging rather than katello in redmine. Would that shut foreman prprocessor?

**Comment by ehelms** [comment]
Nah, I'm not sure why its still doing this. I thought I had re-adjusted the prprocessor to look at the Katello project. I'll find some time to dig more. 

Anyway, thanks for this @lzap !

**Pull request merged**
