### PR TITLE
Bump to RC2

### PR DESCRIPTION
**Pull request by akofink**

### CODE REVIEW

**Review by ehelms — APPROVED** [review]

**Comment by ehelms** [comment]
Technically, we'd bump these when we annex the sources with them as you will see this fail testing because the sources are the old RC1 ones still.

**Comment by akofink** [comment]
Oh okay. I guess we can keep this open as a placeholder for when we have the RPMs.

**Comment by akofink** [comment]
Updated with katello gem and katello-installer source.

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
You need to include https://github.com/Katello/katello-packaging/commit/41590d80577c04a4d42d344fabc146c26857a6c2

**Pull request merged**
