### PR TITLE
Update hammer_cli_csv to 2.1.2

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Review by akofink — APPROVED** [review]
ACK!

**Comment by ehelms** [comment]
Looks like you may need to add to `%files`:

```
%{gem_instdir}/locale
```

**Comment by thomasmckay** [comment]
@ehelms thanks! I did add the locale dir to the gem, which was the source of the problem.

**Comment by thomasmckay** [comment]
(pretty) please release this to katello-3.2 as well as nightly

**Comment by ehelms** [comment]
Thanks @thomasmckay !

**Pull request merged**
